# Generated by Django 5.1.6 on 2025-04-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_video_video_file_alter_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upload', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
